# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Matheus\Documents\GitHub\Minha-Vida-Academica_Desktop\_design\leitor_qr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1715, 952)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 700))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 700))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imgLabel = QtWidgets.QLabel(self.frame_5)
        self.imgLabel.setMinimumSize(QtCore.QSize(1117, 700))
        self.imgLabel.setMaximumSize(QtCore.QSize(1250, 700))
        self.imgLabel.setSizeIncrement(QtCore.QSize(0, 0))
        self.imgLabel.setStyleSheet("")
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.horizontalLayout.addWidget(self.imgLabel)
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.abrir_camera = QtWidgets.QPushButton(self.frame_11)
        self.abrir_camera.setGeometry(QtCore.QRect(70, 0, 100, 100))
        self.abrir_camera.setMinimumSize(QtCore.QSize(100, 100))
        self.abrir_camera.setStyleSheet(
            "QPushButton#abrir_camera{\n"
            "background-image: url(:/newPrefix/camera_branca.png);\n"
            "background-repeat:no-repeat;\n"
            "background-position:center;\n"
            "border: 1px solid white;\n"
            "border-radius: 50px;}\n"
            "QPushButton#abrir_camera:hover:pressed{\n"
            "background-color: rgb(73, 122, 166);\n"
            "}"
        )
        self.abrir_camera.setText("")
        self.abrir_camera.setObjectName("abrir_camera")
        self.fechar_camera = QtWidgets.QPushButton(self.frame_11)
        self.fechar_camera.setGeometry(QtCore.QRect(70, 0, 100, 100))
        self.fechar_camera.setMinimumSize(QtCore.QSize(100, 100))
        self.fechar_camera.setStyleSheet(
            "QPushButton#fechar_camera{\n"
            "background-image: url(:/newPrefix/desligar_camera_branca.png);\n"
            "background-repeat:no-repeat;\n"
            "background-position:center;\n"
            "border: 1px solid white;\n"
            "border-radius: 50px;}\n"
            "QPushButton#fechar_camera:hover:pressed{\n"
            "background-color: rgb(73, 122, 166);\n"
            "}"
        )
        self.fechar_camera.setText("")
        self.fechar_camera.setObjectName("fechar_camera")
        self.sair = QtWidgets.QPushButton(self.frame_11)
        self.sair.setGeometry(QtCore.QRect(240, 0, 100, 100))
        self.sair.setMinimumSize(QtCore.QSize(100, 100))
        self.sair.setStyleSheet(
            "QPushButton#sair{\n"
            "background-image: url(:/newPrefix/sair_branco.png);\n"
            "background-repeat:no-repeat;\n"
            "background-position:center;\n"
            "border: 1px solid white;\n"
            "border-radius: 50px;}\n"
            "QPushButton#sair:hover:pressed{\n"
            "background-color: rgb(73, 122, 166);\n"
            "}"
        )
        self.sair.setText("")
        self.sair.setObjectName("sair")
        self.horizontalLayout_2.addWidget(self.frame_11)
        self.gridLayout_2.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(1691, 70))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame.setStyleSheet("background-color: rgb(73, 122, 166);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.ufopa_2 = QtWidgets.QLabel(self.frame_9)
        self.ufopa_2.setGeometry(QtCore.QRect(70, 0, 151, 71))
        self.ufopa_2.setStyleSheet(
            "text-align: center;\n" "color: rgb(255, 255, 255);\n" "padding-top:-35px;"
        )
        self.ufopa_2.setObjectName("ufopa_2")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 91, 71))
        self.frame_10.setStyleSheet("image: url(:/newPrefix/logo-ufopa-180x180.png);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.frame_user = QtWidgets.QFrame(self.frame)
        self.frame_user.setMinimumSize(QtCore.QSize(540, 0))
        self.frame_user.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_user.setStyleSheet(
            "QFrame#frame_10{\n" "\n" "border:1px solid white;\n" "\n" "}"
        )
        self.frame_user.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_user.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_user.setObjectName("frame_user")
        self.label_user = QtWidgets.QLabel(self.frame_user)
        self.label_user.setGeometry(QtCore.QRect(10, 10, 521, 31))
        self.label_user.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_user.setText("")
        self.label_user.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user.setObjectName("label_user")
        self.horizontalLayout_4.addWidget(self.frame_user)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(550, 724))
        self.frame_4.setMaximumSize(QtCore.QSize(550, 16777215))
        self.frame_4.setSizeIncrement(QtCore.QSize(50, 0))
        self.frame_4.setStyleSheet("background-color: rgb(255,255,255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 700))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 700))
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.campus_all = QtWidgets.QFrame(self.frame_6)
        self.campus_all.setGeometry(QtCore.QRect(0, 10, 511, 681))
        self.campus_all.setStyleSheet("")
        self.campus_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.campus_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.campus_all.setObjectName("campus_all")
        self.curso = QtWidgets.QLabel(self.campus_all)
        self.curso.setGeometry(QtCore.QRect(40, 301, 451, 41))
        self.curso.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.curso.setObjectName("curso")
        self.hora_ini = QtWidgets.QLabel(self.campus_all)
        self.hora_ini.setGeometry(QtCore.QRect(40, 439, 221, 41))
        self.hora_ini.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.hora_ini.setObjectName("hora_ini")
        self.observacao = QtWidgets.QLabel(self.campus_all)
        self.observacao.setGeometry(QtCore.QRect(40, 486, 451, 61))
        self.observacao.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.observacao.setAlignment(QtCore.Qt.AlignCenter)
        self.observacao.setObjectName("observacao")
        self.espaco_reservado = QtWidgets.QLabel(self.campus_all)
        self.espaco_reservado.setGeometry(QtCore.QRect(40, 347, 451, 41))
        self.espaco_reservado.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.espaco_reservado.setObjectName("espaco_reservado")
        self.negar = QtWidgets.QPushButton(self.campus_all)
        self.negar.setGeometry(QtCore.QRect(160, 581, 81, 61))
        self.negar.setStyleSheet(
            ".QPushButton#negar {\n"
            "    color: white;\n"
            "    text-align: center;\n"
            "    text-decoration: none;\n"
            "    display: inline-block;\n"
            "    font-size: 25px;\n"
            "    margin: 4px 2px;\n"
            "    cursor: pointer;\n"
            "    background-color: white; \n"
            "    color: red; \n"
            "    border: 2px solid red;\n"
            "    border-radius: 50px;\n"
            "}\n"
            "\n"
            ".QPushButton#negar:hover:pressed {\n"
            "    background-color:red;\n"
            "    color: white;\n"
            "    border-top-color: rgb(255, 255, 255);\n"
            "    border-right-color: rgb(0,0,0);\n"
            "    border-bottom-color: rgb(0,0,0);\n"
            "    border-left-color: rgb(255, 255, 255);\n"
            "}\n"
            ""
        )
        self.negar.setObjectName("negar")
        self.frame_12 = QtWidgets.QFrame(self.campus_all)
        self.frame_12.setGeometry(QtCore.QRect(190, 10, 141, 151))
        self.frame_12.setStyleSheet(
            "image: url(:/newPrefix/logo-normal.jpg);\n"
            "background-repeat: no-repeat;\n"
            "background-position:center;"
        )
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.matricula = QtWidgets.QLabel(self.campus_all)
        self.matricula.setGeometry(QtCore.QRect(40, 254, 451, 41))
        self.matricula.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.matricula.setObjectName("matricula")
        self.label_2 = QtWidgets.QLabel(self.campus_all)
        self.label_2.setGeometry(QtCore.QRect(70, 163, 381, 31))
        self.label_2.setStyleSheet(
            'font: 75 16pt "Arial";\n' "color: rgb(73, 122, 166);"
        )
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.nome_aluno = QtWidgets.QLabel(self.campus_all)
        self.nome_aluno.setGeometry(QtCore.QRect(40, 206, 451, 41))
        self.nome_aluno.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.nome_aluno.setObjectName("nome_aluno")
        self.hora_fim = QtWidgets.QLabel(self.campus_all)
        self.hora_fim.setGeometry(QtCore.QRect(270, 439, 221, 41))
        self.hora_fim.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.hora_fim.setObjectName("hora_fim")
        self.afirmar = QtWidgets.QPushButton(self.campus_all)
        self.afirmar.setGeometry(QtCore.QRect(65, 581, 81, 61))
        self.afirmar.setStyleSheet(
            ".QPushButton#afirmar {\n"
            "    color: white;\n"
            "    text-align: center;\n"
            "    text-decoration: none;\n"
            "    display: inline-block;\n"
            "    font-size: 25px;\n"
            "    margin: 4px 2px;\n"
            "    cursor: pointer;\n"
            "    background-color: white; \n"
            "    color: #4CAF50; \n"
            "    border: 2px solid #4CAF50;\n"
            "}\n"
            "\n"
            ".QPushButton#afirmar:hover:pressed {\n"
            "    background-color: #4CAF50;\n"
            "    color: white;\n"
            "    border-top-color: rgb(255, 255, 255);\n"
            "    border-right-color: rgb(0,0,0);\n"
            "    border-bottom-color: rgb(0,0,0);\n"
            "    border-left-color: rgb(255, 255, 255);\n"
            "}\n"
            ""
        )
        self.afirmar.setObjectName("afirmar")
        self.data = QtWidgets.QLabel(self.campus_all)
        self.data.setGeometry(QtCore.QRect(40, 393, 451, 41))
        self.data.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.data.setObjectName("data")
        self.s_dose_all = QtWidgets.QFrame(self.campus_all)
        self.s_dose_all.setGeometry(QtCore.QRect(390, 594, 101, 71))
        self.s_dose_all.setStyleSheet(
            "QFrame#s_dose_all{\n" "border: 2px solid black;\n" "}\n" "\n" ""
        )
        self.s_dose_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.s_dose_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.s_dose_all.setObjectName("s_dose_all")
        self.fig_vac_2 = QtWidgets.QFrame(self.s_dose_all)
        self.fig_vac_2.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.fig_vac_2.setStyleSheet("image: url(:/newPrefix/2646111.png);\n" "\n" "")
        self.fig_vac_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fig_vac_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fig_vac_2.setObjectName("fig_vac_2")
        self.s_dose_n = QtWidgets.QLabel(self.s_dose_all)
        self.s_dose_n.setGeometry(QtCore.QRect(50, 10, 41, 41))
        self.s_dose_n.setStyleSheet("")
        self.s_dose_n.setAlignment(QtCore.Qt.AlignCenter)
        self.s_dose_n.setObjectName("s_dose_n")
        self.p_dose_all = QtWidgets.QFrame(self.campus_all)
        self.p_dose_all.setGeometry(QtCore.QRect(270, 594, 101, 71))
        self.p_dose_all.setStyleSheet(
            "QFrame#p_dose_all{\n" "border: 2px solid black;\n" "}\n" "\n" ""
        )
        self.p_dose_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p_dose_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p_dose_all.setObjectName("p_dose_all")
        self.fig_vac_1 = QtWidgets.QFrame(self.p_dose_all)
        self.fig_vac_1.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.fig_vac_1.setStyleSheet("image: url(:/newPrefix/2646111.png);\n" "\n" "")
        self.fig_vac_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fig_vac_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fig_vac_1.setObjectName("fig_vac_1")
        self.p_dose_n = QtWidgets.QLabel(self.p_dose_all)
        self.p_dose_n.setGeometry(QtCore.QRect(50, 10, 41, 41))
        self.p_dose_n.setStyleSheet("")
        self.p_dose_n.setAlignment(QtCore.Qt.AlignCenter)
        self.p_dose_n.setObjectName("p_dose_n")
        self.label_3 = QtWidgets.QLabel(self.campus_all)
        self.label_3.setGeometry(QtCore.QRect(290, 560, 161, 31))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.fechar_confirma = QtWidgets.QLabel(self.campus_all)
        self.fechar_confirma.setGeometry(QtCore.QRect(65, 581, 81, 61))
        self.fechar_confirma.setStyleSheet(
            "    text-align: center;\n"
            "    text-decoration: none;\n"
            "    display: inline-block;\n"
            "    font-size: 25px;\n"
            "    margin: 4px 2px;\n"
            "    cursor: pointer;\n"
            "    background-color: white; \n"
            "    color: rgb(73, 122, 166); \n"
            "    border: 2px solid rgb(73, 122, 166);"
        )
        self.fechar_confirma.setAlignment(QtCore.Qt.AlignCenter)
        self.fechar_confirma.setObjectName("fechar_confirma")
        self.fechar_negar = QtWidgets.QLabel(self.campus_all)
        self.fechar_negar.setGeometry(QtCore.QRect(160, 581, 81, 61))
        self.fechar_negar.setStyleSheet(
            "    text-align: center;\n"
            "    text-decoration: none;\n"
            "    display: inline-block;\n"
            "    font-size: 25px;\n"
            "    margin: 4px 2px;\n"
            "    cursor: pointer;\n"
            "    background-color: white; \n"
            "    color: rgb(73, 122, 166); \n"
            "    border: 2px solid rgb(73, 122, 166);"
        )
        self.fechar_negar.setAlignment(QtCore.Qt.AlignCenter)
        self.fechar_negar.setObjectName("fechar_negar")
        self.campus_restricao = QtWidgets.QFrame(self.frame_6)
        self.campus_restricao.setGeometry(QtCore.QRect(0, 10, 511, 681))
        self.campus_restricao.setStyleSheet("")
        self.campus_restricao.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.campus_restricao.setFrameShadow(QtWidgets.QFrame.Raised)
        self.campus_restricao.setObjectName("campus_restricao")
        self.curso_r = QtWidgets.QLabel(self.campus_restricao)
        self.curso_r.setGeometry(QtCore.QRect(40, 369, 451, 41))
        self.curso_r.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.curso_r.setObjectName("curso_r")
        self.hora_ini_r = QtWidgets.QLabel(self.campus_restricao)
        self.hora_ini_r.setGeometry(QtCore.QRect(270, 426, 221, 41))
        self.hora_ini_r.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.hora_ini_r.setObjectName("hora_ini_r")
        self.frame_14 = QtWidgets.QFrame(self.campus_restricao)
        self.frame_14.setGeometry(QtCore.QRect(190, 20, 141, 151))
        self.frame_14.setStyleSheet(
            "image: url(:/newPrefix/logo-normal.jpg);\n"
            "background-repeat: no-repeat;\n"
            "background-position:center;"
        )
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.matricula_r = QtWidgets.QLabel(self.campus_restricao)
        self.matricula_r.setGeometry(QtCore.QRect(40, 312, 451, 41))
        self.matricula_r.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.matricula_r.setObjectName("matricula_r")
        self.label_r = QtWidgets.QLabel(self.campus_restricao)
        self.label_r.setGeometry(QtCore.QRect(70, 180, 381, 61))
        self.label_r.setStyleSheet(
            'font: 75 16pt "Arial";\n' "color: rgb(73, 122, 166);"
        )
        self.label_r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r.setObjectName("label_r")
        self.nome_aluno_r = QtWidgets.QLabel(self.campus_restricao)
        self.nome_aluno_r.setGeometry(QtCore.QRect(40, 259, 451, 41))
        self.nome_aluno_r.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.nome_aluno_r.setObjectName("nome_aluno_r")
        self.data_r = QtWidgets.QLabel(self.campus_restricao)
        self.data_r.setGeometry(QtCore.QRect(40, 426, 221, 41))
        self.data_r.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.data_r.setObjectName("data_r")
        self.label_6 = QtWidgets.QLabel(self.campus_restricao)
        self.label_6.setGeometry(QtCore.QRect(247, 543, 220, 40))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.observacao_r = QtWidgets.QLabel(self.campus_restricao)
        self.observacao_r.setGeometry(QtCore.QRect(40, 480, 451, 61))
        self.observacao_r.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(145, 145, 145);\n"
            'font: 75 12pt "Arial";\n'
            "padding-top:5px;\n"
            "padding-left: 5px;\n"
            "border-color: rgb(0, 0, 0);\n"
            "border: 1px solid;"
        )
        self.observacao_r.setAlignment(QtCore.Qt.AlignCenter)
        self.observacao_r.setObjectName("observacao_r")
        self.s_dose = QtWidgets.QFrame(self.campus_restricao)
        self.s_dose.setGeometry(QtCore.QRect(370, 590, 101, 71))
        self.s_dose.setStyleSheet(
            "QFrame#s_dose{\n" "border: 2px solid black;\n" "}\n" "\n" ""
        )
        self.s_dose.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.s_dose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.s_dose.setObjectName("s_dose")
        self.fig_vac_r_2 = QtWidgets.QFrame(self.s_dose)
        self.fig_vac_r_2.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.fig_vac_r_2.setStyleSheet("image: url(:/newPrefix/2646111.png);\n" "\n" "")
        self.fig_vac_r_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fig_vac_r_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fig_vac_r_2.setObjectName("fig_vac_r_2")
        self.s_dose_n_r = QtWidgets.QLabel(self.s_dose)
        self.s_dose_n_r.setGeometry(QtCore.QRect(50, 10, 41, 41))
        self.s_dose_n_r.setStyleSheet("")
        self.s_dose_n_r.setAlignment(QtCore.Qt.AlignCenter)
        self.s_dose_n_r.setObjectName("s_dose_n_r")
        self.p_dose = QtWidgets.QFrame(self.campus_restricao)
        self.p_dose.setGeometry(QtCore.QRect(240, 590, 101, 71))
        self.p_dose.setStyleSheet(
            "QFrame#p_dose{\n" "border: 2px solid black;\n" "}\n" "\n" ""
        )
        self.p_dose.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.p_dose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.p_dose.setObjectName("p_dose")
        self.fig_vac_r = QtWidgets.QFrame(self.p_dose)
        self.fig_vac_r.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.fig_vac_r.setStyleSheet("image: url(:/newPrefix/2646111.png);\n" "\n" "")
        self.fig_vac_r.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fig_vac_r.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fig_vac_r.setObjectName("fig_vac_r")
        self.p_dose_n_r = QtWidgets.QLabel(self.p_dose)
        self.p_dose_n_r.setGeometry(QtCore.QRect(50, 10, 41, 41))
        self.p_dose_n_r.setStyleSheet("")
        self.p_dose_n_r.setAlignment(QtCore.Qt.AlignCenter)
        self.p_dose_n_r.setObjectName("p_dose_n_r")
        self.confirmar = QtWidgets.QPushButton(self.campus_restricao)
        self.confirmar.setGeometry(QtCore.QRect(63, 587, 131, 71))
        self.confirmar.setStyleSheet(
            ".QPushButton#confirmar {\n"
            "    color: white;\n"
            "    text-align: center;\n"
            "    text-decoration: none;\n"
            "    display: inline-block;\n"
            "    font-size: 20px;\n"
            "    margin: 4px 2px;\n"
            "    cursor: pointer;\n"
            "    background-color: white; \n"
            "    color: #4CAF50; \n"
            "    border: 2px solid #4CAF50;\n"
            "}\n"
            "\n"
            ".QPushButton#confirmar:hover:pressed {\n"
            "    background-color: #4CAF50;\n"
            "    color: white;\n"
            "    border-top-color: rgb(255, 255, 255);\n"
            "    border-right-color: rgb(0,0,0);\n"
            "    border-bottom-color: rgb(0,0,0);\n"
            "    border-left-color: rgb(255, 255, 255);\n"
            "}\n"
            ""
        )
        self.confirmar.setObjectName("confirmar")
        self.temp = QtWidgets.QFrame(self.frame_6)
        self.temp.setGeometry(QtCore.QRect(130, 210, 301, 241))
        self.temp.setStyleSheet(
            "QFrame#temp{\n"
            "border: 2px solid rgb(73, 122, 166);\n"
            "background-color: white;\n"
            "}"
        )
        self.temp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.temp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.temp.setObjectName("temp")
        self.temperatura = QtWidgets.QLineEdit(self.temp)
        self.temperatura.setGeometry(QtCore.QRect(90, 110, 111, 41))
        self.temperatura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.temperatura.setAlignment(QtCore.Qt.AlignCenter)
        self.temperatura.setObjectName("temperatura")
        self.aviso_2 = QtWidgets.QLabel(self.temp)
        self.aviso_2.setGeometry(QtCore.QRect(30, 30, 231, 31))
        self.aviso_2.setStyleSheet(
            "color: rgb(73, 122, 166);\n"
            'font: 75 14pt "Arial";\n'
            "background-color: white;"
        )
        self.aviso_2.setAlignment(QtCore.Qt.AlignCenter)
        self.aviso_2.setObjectName("aviso_2")
        self.enviar_temp = QtWidgets.QPushButton(self.temp)
        self.enviar_temp.setGeometry(QtCore.QRect(110, 170, 81, 51))
        self.enviar_temp.setStyleSheet(
            "QPushButton#enviar_temp{background-color:rgb(73, 122, 166);\n"
            "color: rgb(255, 255, 255);\n"
            'font: 87 9pt "Arial Black";\n'
            "border: 1.5px solid rgb(255, 255, 255);}\n"
            "QPushButton#enviar_temp:hover:pressed{\n"
            "background-color: rgb(255, 255, 255);\n"
            "color: rgb(73, 122, 166);\n"
            "border: 1.5px solid rgb(73, 122, 166);\n"
            "}"
        )
        self.enviar_temp.setObjectName("enviar_temp")
        self.aviso_1 = QtWidgets.QLabel(self.temp)
        self.aviso_1.setGeometry(QtCore.QRect(50, 70, 191, 20))
        self.aviso_1.setStyleSheet(
            "color:  rgb(73, 122, 166);\n"
            'font: 75 14pt "Arial";\n'
            "background-color: white;"
        )
        self.aviso_1.setAlignment(QtCore.Qt.AlignCenter)
        self.aviso_1.setObjectName("aviso_1")
        self.aviso_temp = QtWidgets.QFrame(self.frame_6)
        self.aviso_temp.setGeometry(QtCore.QRect(130, 240, 291, 191))
        self.aviso_temp.setStyleSheet(
            "QFrame#aviso_temp{\n"
            "border:2px solid rgb(73, 122, 166);;\n"
            "background-color: white;\n"
            "}"
        )
        self.aviso_temp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.aviso_temp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aviso_temp.setObjectName("aviso_temp")
        self.label = QtWidgets.QLabel(self.aviso_temp)
        self.label.setGeometry(QtCore.QRect(40, 30, 221, 71))
        self.label.setStyleSheet(
            "color: rgb(73, 122, 166);\n"
            'font: 75 14pt "Arial";\n'
            "background-color: white;"
        )
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.sim = QtWidgets.QPushButton(self.aviso_temp)
        self.sim.setGeometry(QtCore.QRect(50, 120, 81, 51))
        self.sim.setStyleSheet(
            ".QPushButton#sim {\n"
            "    color: white;\n"
            "    text-align: center;\n"
            "    text-decoration: none;\n"
            "    display: inline-block;\n"
            "    font-size: 25px;\n"
            "    margin: 4px 2px;\n"
            "    cursor: pointer;\n"
            "    background-color: white; \n"
            "    color: #4CAF50; \n"
            "    border: 2px solid #4CAF50;\n"
            "}\n"
            "\n"
            ".QPushButton#sim:hover:pressed {\n"
            "    background-color: #4CAF50;\n"
            "    color: white;\n"
            "    border-top-color: rgb(255, 255, 255);\n"
            "    border-right-color: rgb(0,0,0);\n"
            "    border-bottom-color: rgb(0,0,0);\n"
            "    border-left-color: rgb(255, 255, 255);\n"
            "}\n"
            ""
        )
        self.sim.setObjectName("sim")
        self.nao = QtWidgets.QPushButton(self.aviso_temp)
        self.nao.setGeometry(QtCore.QRect(160, 120, 81, 51))
        self.nao.setStyleSheet(
            ".QPushButton#nao {\n"
            "    color: white;\n"
            "    text-align: center;\n"
            "    text-decoration: none;\n"
            "    display: inline-block;\n"
            "    font-size: 25px;\n"
            "    margin: 4px 2px;\n"
            "    cursor: pointer;\n"
            "    background-color: white; \n"
            "    color: red; \n"
            "    border: 2px solid red;\n"
            "    border-radius: 50px;\n"
            "}\n"
            "\n"
            ".QPushButton#nao:hover:pressed {\n"
            "    background-color:red;\n"
            "    color: white;\n"
            "    border-top-color: rgb(255, 255, 255);\n"
            "    border-right-color: rgb(0,0,0);\n"
            "    border-bottom-color: rgb(0,0,0);\n"
            "    border-left-color: rgb(255, 255, 255);\n"
            "}\n"
            ""
        )
        self.nao.setObjectName("nao")
        self.CAPA = QtWidgets.QFrame(self.frame_6)
        self.CAPA.setGeometry(QtCore.QRect(0, 0, 511, 691))
        self.CAPA.setStyleSheet("background-color: white;\n" "\n" "")
        self.CAPA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CAPA.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CAPA.setObjectName("CAPA")
        self.frame_7 = QtWidgets.QFrame(self.CAPA)
        self.frame_7.setGeometry(QtCore.QRect(110, 40, 311, 291))
        self.frame_7.setStyleSheet(
            "image: url(:/newPrefix/logo-normal.jpg);\n"
            "background-repeat: no-repeat;\n"
            "background-position: center;"
        )
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_4 = QtWidgets.QLabel(self.CAPA)
        self.label_4.setGeometry(QtCore.QRect(70, 320, 391, 261))
        self.label_4.setStyleSheet(
            'font: 75 14pt "Arial";\n' "color: rgb(73, 122, 166);"
        )
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.regi_saida = QtWidgets.QFrame(self.CAPA)
        self.regi_saida.setGeometry(QtCore.QRect(70, 120, 401, 251))
        self.regi_saida.setStyleSheet(
            "QFrame#regi_saida{\n"
            "\n"
            "border:1px solid rgb(255, 255, 255);\n"
            "background-color: rgb(73, 122, 166);\n"
            "\n"
            "}"
        )
        self.regi_saida.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.regi_saida.setFrameShadow(QtWidgets.QFrame.Raised)
        self.regi_saida.setObjectName("regi_saida")
        self.text_saida = QtWidgets.QLabel(self.regi_saida)
        self.text_saida.setGeometry(QtCore.QRect(20, 50, 351, 151))
        self.text_saida.setStyleSheet(
            "color: rgb(255, 255, 255);\n" "background-color: rgb(73, 122, 166);"
        )
        self.text_saida.setAlignment(QtCore.Qt.AlignCenter)
        self.text_saida.setObjectName("text_saida")
        self.campus_restricao.raise_()
        self.campus_all.raise_()
        self.temp.raise_()
        self.aviso_temp.raise_()
        self.CAPA.raise_()
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Minha Vida Acadêmica"))
        self.ufopa_2.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:20pt; font-weight:600;">UFOPA</span></p></body></html>',
            )
        )
        self.curso.setText(_translate("MainWindow", "Curso"))
        self.hora_ini.setText(_translate("MainWindow", "Entrada"))
        self.observacao.setText(_translate("MainWindow", "Observação"))
        self.espaco_reservado.setText(_translate("MainWindow", "Espaço Reservado"))
        self.negar.setText(_translate("MainWindow", "✖"))
        self.matricula.setText(_translate("MainWindow", "Matricula"))
        self.label_2.setText(_translate("MainWindow", "Informações do Aluno"))
        self.nome_aluno.setText(_translate("MainWindow", "Nome do Aluno"))
        self.hora_fim.setText(_translate("MainWindow", "Saída"))
        self.afirmar.setToolTip(_translate("MainWindow", "Afirmar"))
        self.afirmar.setWhatsThis(_translate("MainWindow", "Afirmar"))
        self.afirmar.setText(_translate("MainWindow", "✔"))
        self.data.setText(_translate("MainWindow", "Data Reservada"))
        self.s_dose_n.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:14pt;">2ª</span></p></body></html>',
            )
        )
        self.p_dose_n.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:14pt;">1ª</span></p></body></html>',
            )
        )
        self.label_3.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:9pt; font-weight:600;">Quantidade de Doses</span></p></body></html>',
            )
        )
        self.fechar_confirma.setText(_translate("MainWindow", "✔"))
        self.fechar_negar.setText(_translate("MainWindow", "✖"))
        self.curso_r.setText(_translate("MainWindow", "Curso"))
        self.hora_ini_r.setText(_translate("MainWindow", "Hora da Entrada"))
        self.matricula_r.setText(_translate("MainWindow", "Matricula"))
        self.label_r.setText(_translate("MainWindow", "Informações do Aluno"))
        self.nome_aluno_r.setText(_translate("MainWindow", "Nome do Aluno"))
        self.data_r.setText(_translate("MainWindow", "Data"))
        self.label_6.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:9pt; font-weight:600;">Quantidade de Doses</span></p></body></html>',
            )
        )
        self.observacao_r.setText(_translate("MainWindow", "Observação"))
        self.s_dose_n_r.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:14pt;">2ª</span></p></body></html>',
            )
        )
        self.p_dose_n_r.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:14pt;">1ª</span></p></body></html>',
            )
        )
        self.confirmar.setText(_translate("MainWindow", "Confirmar"))
        self.temperatura.setInputMask(_translate("MainWindow", "99.99"))
        self.aviso_2.setText(_translate("MainWindow", "Insira a temperatura"))
        self.enviar_temp.setText(_translate("MainWindow", "ENVIAR"))
        self.aviso_1.setText(_translate("MainWindow", "Apenas Números"))
        self.label.setText(_translate("MainWindow", "Deseja enviar\n" "Temperatura?"))
        self.sim.setText(_translate("MainWindow", "✔"))
        self.nao.setText(_translate("MainWindow", "❌"))
        self.label_4.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><span style=" font-size:16pt; font-weight:600;">SISTEMA DE CONTROLE</span></p><p align="center"><span style=" font-size:16pt; font-weight:600;">DE ACESSO AO CAMPUS</span><br/></p><p align="center">MINHA VIDA ACADÊMICA</p></body></html>',
            )
        )
        self.text_saida.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><br/></p></body></html>',
            )
        )


import imagens_rc
