# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Matheus\Documents\GitHub\Minha-Vida-Academica_Desktop\dist\MVA\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.setEnabled(True)
        Dialog.resize(1000, 900)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1000, 900))
        Dialog.setMaximumSize(QtCore.QSize(1000, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off
        )
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);\n" "")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setMinimumSize(QtCore.QSize(1000, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(1000, 100))
        self.frame_4.setStyleSheet("background-color:  rgb(73, 122, 166);\n" "")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(20, 10, 91, 71))
        self.frame_6.setStyleSheet("image: url(:/newPrefix/logo-ufopa-180x180.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.ufopa_2 = QtWidgets.QLabel(self.frame_4)
        self.ufopa_2.setGeometry(QtCore.QRect(100, 20, 151, 71))
        self.ufopa_2.setStyleSheet(
            "text-align: center;\n" "color: rgb(255, 255, 255);\n" "padding-top:-35px;"
        )
        self.ufopa_2.setObjectName("ufopa_2")
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 700))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 700))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setMaximumSize(QtCore.QSize(250, 700))
        self.frame_9.setStyleSheet(
            "image: url(:/newPrefix/MVA hand 2.png);\n" "padding-bottom:-350px;"
        )
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout.addWidget(self.frame_9)
        self.div = QtWidgets.QFrame(self.frame_2)
        self.div.setMinimumSize(QtCore.QSize(0, 570))
        self.div.setMaximumSize(QtCore.QSize(500, 570))
        self.div.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.div.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" "border-radius: 15px;\n" ""
        )
        self.div.setFrameShape(QtWidgets.QFrame.Box)
        self.div.setFrameShadow(QtWidgets.QFrame.Raised)
        self.div.setObjectName("div")
        self.ufopa = QtWidgets.QLabel(self.div)
        self.ufopa.setGeometry(QtCore.QRect(50, 100, 401, 191))
        self.ufopa.setStyleSheet("text-align: center;")
        self.ufopa.setObjectName("ufopa")
        self.frame_3 = QtWidgets.QFrame(self.div)
        self.frame_3.setGeometry(QtCore.QRect(200, 10, 120, 120))
        self.frame_3.setStyleSheet(
            "image: url(:/newPrefix/logo-100-100.jpg);\n" "border-radius:50px;"
        )
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.usuario = QtWidgets.QLineEdit(self.div)
        self.usuario.setGeometry(QtCore.QRect(110, 320, 331, 51))
        self.usuario.setStyleSheet(
            "QLineEdit{\n"
            '    font: 12pt "Arial";\n'
            "    border: 1px solid rgb(0,0,0);\n"
            "    border-radius: 0px;\n"
            "    color: rgb(0,0,0);\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    background-color: rgba(175, 171, 171, 0.3);\n"
            "}"
        )
        self.usuario.setMaxLength(40)
        self.usuario.setObjectName("usuario")
        self.senha = QtWidgets.QLineEdit(self.div)
        self.senha.setGeometry(QtCore.QRect(110, 390, 331, 51))
        self.senha.setStyleSheet(
            "QLineEdit{\n"
            '    font: 12pt "Arial";\n'
            "    border: 1px solid rgb(0,0,0);\n"
            "    border-radius: 0px;\n"
            "    color: rgb(0,0,0);\n"
            "}\n"
            "QLineEdit:hover{\n"
            "    background-color: rgba(175, 171, 171, 0.3);\n"
            "}"
        )
        self.senha.setMaxLength(8)
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha.setObjectName("senha")
        self.frame_5 = QtWidgets.QFrame(self.div)
        self.frame_5.setGeometry(QtCore.QRect(50, 320, 51, 51))
        self.frame_5.setStyleSheet("image: url(:/newPrefix/usuario.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_7 = QtWidgets.QFrame(self.div)
        self.frame_7.setGeometry(QtCore.QRect(50, 380, 51, 61))
        self.frame_7.setStyleSheet(
            "background-image: url(:/newPrefix/cadeado-preto.png);\n"
            "background-repeat: no-repeat;\n"
            "background-position: center;"
        )
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.enviar = QtWidgets.QPushButton(self.div)
        self.enviar.setGeometry(QtCore.QRect(190, 470, 131, 51))
        self.enviar.setStyleSheet(
            "QPushButton#enviar{background-color:  rgb(73, 122, 166);\n"
            "color: rgb(255, 255, 255);\n"
            'font: 87 9pt "Arial Black";\n'
            "border:none;\n"
            "border-radius:0px;}\n"
            "QPushButton#enviar:hover:pressed{\n"
            "background-color: rgb(255, 255, 255);\n"
            "color:  rgb(73, 122, 166);\n"
            "border: 1.5px solid  rgb(73, 122, 166);\n"
            "}"
        )
        self.enviar.setObjectName("enviar")
        self.aviso = QtWidgets.QLabel(self.div)
        self.aviso.setGeometry(QtCore.QRect(60, 270, 391, 41))
        self.aviso.setStyleSheet("color: rgb(0, 0, 0);\n" 'font: 75 12pt "Arial";')
        self.aviso.setText("")
        self.aviso.setAlignment(QtCore.Qt.AlignCenter)
        self.aviso.setObjectName("aviso")
        self.horizontalLayout.addWidget(self.div)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setMaximumSize(QtCore.QSize(250, 700))
        self.frame_8.setStyleSheet(
            "image: url(:/newPrefix/MVA hand.png);\n" "padding-top:-350px;"
        )
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(1000, 100))
        self.frame.setMaximumSize(QtCore.QSize(1000, 100))
        self.frame.setStyleSheet("background-color:  rgb(73, 122, 166);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ufopa_3 = QtWidgets.QLabel(self.frame)
        self.ufopa_3.setGeometry(QtCore.QRect(30, 20, 261, 61))
        self.ufopa_3.setStyleSheet("color:  rgb(255, 255, 255);")
        self.ufopa_3.setObjectName("ufopa_3")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MInha Vida Acadêmica"))
        Dialog.setWhatsThis(
            _translate("Dialog", "<html><head/><body><p><br/></p></body></html>")
        )
        self.ufopa_2.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p align="center"><span style=" font-size:20pt; font-weight:600;">UFOPA</span></p></body></html>',
            )
        )
        self.ufopa.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p align="center"><span style=" font-size:20pt; font-weight:600;">SISTEMA DE CONTROLE</span></p><p align="center"><span style=" font-size:20pt; font-weight:600;">DE ACESSO</span></p><p align="center"><span style=" font-size:12pt; font-weight:600;">Minha Vida Acadêmica</span></p></body></html>',
            )
        )
        self.usuario.setPlaceholderText(_translate("Dialog", "Digite seu usuário"))
        self.senha.setPlaceholderText(_translate("Dialog", "Digite sua senha"))
        self.enviar.setText(_translate("Dialog", "ENVIAR"))
        self.ufopa_3.setText(
            _translate(
                "Dialog",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                '<p style=" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:9pt;">Copyright © 2021. All rights reserved.</span></p></body></html>',
            )
        )


import imagens_rc
